mongo-url: localhost:27017
api-addr: localhost:8080
auth-username: admin
auth-password: example-passwd
#elasticsearch-addr: localhost:9200
# For locally running services.
identity-public-key: CIdWcEUN+0OZnKW9KwruRQnQDY/qqzVdD30CijwiWCk=
identity-location: http://localhost:8081/v1/discharger
identity-api-url: http://localhost:8081
# For production identity manager.
#identity-public-key: hmHaPgCC1UfuhYHUSX5+aihSAZesqpVdjRv0mgfIwjo=
#identity-location: https://api.jujucharms.com/identity/v1/discharger
# Agent credentials.
#agent-name: charmstore@admin@idm
#agent-key:
#  private: 85ZQqTnqiNdEggFVy7TGjRDGMulJHHz8UKkfVl5tTu8=
#  public: X3Yj/aThvG20FoBhRAIX+JbFk300r9Roc2D78r/37iw=
# Statistics Cache maximum age, default 1 hour
#stats-cache-max-age: 1h
#request-timeout: 500ms
#search-cache-max-age: 0s
